[project]
name = "gphix"
version = "1.1.0"
description = "A toolbox to edit and fix issues with GPX files."
readme = "README.md"
authors = [
    { name = "Aggrathon", email = "antonbjo@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "rasterio>=1.5.0",
    "scipy>=1.18.0",
]

[project.scripts]
gphix = "gphix.cli:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.15.2",
    "numpy>=2.5.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.0",
    "snakeviz>=2.2.2",
]

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=95"

[tool.coverage.run]
omit = [
    "tests/*"
]
